FROM node:18-alpine3.15

# Set working directory
RUN mkdir -p /var/www/nestopenia
WORKDIR /var/www/nestopenia

# Copiar el directorio y su contenido
COPY . ./var/www/nestopenia
COPY package.json tsconfig.json tsconfig.build.json /var/www/nestopenia/
RUN yarn install --prod
RUN yarn build


# Dar permiso para ejecutar la applicación
RUN adduser --disabled-password openiauser
RUN chown -R openiauser:openiauser /var/www/nestopenia
USER openiauser

# Limpiar el caché
RUN yarn cache clean --force

EXPOSE 3000

CMD [ "yarn","start" ]