branch-defaults:
  master:
    environment: Damc-v0-api-env
environment-defaults:
  Damc-v0-api-env:
    branch: master
    repository: https://github.com/reyduar/nest-open-ia
global:
  application_name: damc-v0-api
  default_ec2_keyname: null
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
